const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const root=path.resolve(__dirname,'..');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const dashboard=fs.readFileSync(path.join(root,'dashboard.html'),'utf8');

test('Michele book workflow has durable project chapter snapshot rewrite and conversation tables',()=>{
  for(const table of ['book_projects','book_chapters','chapter_versions','editor_notes','michele_feedback','author_voice_profile','rewrite_jobs','book_conversation_sessions','book_conversation_turns']){
    assert.match(server,new RegExp(`create table if not exists ${table}`));
  }
  assert.match(server,/MICHELE_MASTER_MANUSCRIPT_DOC_ID/);
  assert.match(server,/MICHELE_READING_COPY_DOC_ID/);
  assert.match(server,/saveChapterSnapshot/);
  assert.match(server,/Snapshot before Michele approved draft write/);
});

test('Michele chapter sync uses Heading 1 chapter boundaries and preserves snapshots before writes',()=>{
  assert.match(server,/function isMicheleChapterHeading/);
  assert.match(server,/function googleDocStructuralElements/);
  assert.match(server,/documentTab\?\.body\?\.content/);
  assert.match(server,/includeTabsContent:'true'/);
  assert.match(server,/function googleDocWithExportFallback/);
  assert.match(server,/namedStyleType==='HEADING_1'/);
  assert.match(server,/text\.length<=220/);
  assert.match(server,/api\/michele\/book\/admin\/config/);
  assert.match(server,/function writeMicheleChapterResult/);
  assert.match(server,/Refusing to edit the original source manuscript/);
  assert.match(server,/readingId===masterId/);
  assert.match(server,/verifyMicheleOutputWrite/);
  assert.match(server,/normalizeMicheleVerificationText/);
  assert.match(server,/micheleOutputHeadingCandidates/);
  assert.match(server,/micheleChapterHeadingText\(chapter\)/);
  assert.match(server,/Chapter #\$\{num\}/);
  assert.match(server,/Chapter \$\{num\}/);
  assert.match(server,/headingVerified:true/);
  assert.match(server,/contentVerified:true/);
  assert.match(server,/Verification details: heading/);
  assert.match(server,/replaceMicheleOutputChapterOnly/);
  assert.match(server,/micheleOutputPlacementPreflight/);
  assert.match(server,/michelePlacementRequiredResult/);
  assert.match(server,/placementRequired:true/);
  assert.match(server,/Place at beginning/);
  assert.match(server,/Place at end/);
  assert.match(server,/findMicheleOutputChapter/);
  assert.match(server,/micheleForbiddenManuscriptContent/);
  assert.match(server,/micheleWordCount/);
  assert.match(server,/This edit would greatly increase the document length\. I’m stopping this so the manuscript is not accidentally duplicated\./);
  assert.match(server,/Selected chapter was not found in the fresh manuscript document\. I need to know where to place it\./);
  assert.match(server,/before_fresh_doc_write/);
  assert.match(server,/before_fresh_doc_insert/);
  assert.match(server,/replace_chapter_section/);
  assert.match(server,/formatGoogleDocForManuscript/);
  assert.match(server,/updateDocumentStyle/);
  assert.match(server,/alignment:'START'/);
  assert.match(server,/indentStart:zeroPt/);
  assert.match(server,/indentEnd:zeroPt/);
  assert.match(server,/indentFirstLine:zeroPt/);
  assert.match(server,/app\.post\('\/api\/michele\/book\/admin\/format-output',requirePermission\('settings:manage'\)/);
  assert.match(server,/michele_book_output_formatted/);
  assert.match(server,/originalManuscriptEdited:false/);
  assert.match(server,/The original manuscript was not edited/);
  assert.match(server,/function parseMicheleChapterHeading/);
  assert.match(server,/function splitMicheleHeadingTitleAndBody/);
  assert.match(server,/function sanitizeMicheleChapterTitle/);
  assert.match(server,/bodyRemainder/);
  assert.match(server,/There\[’'\]\?s\|There is\|There are/);
  assert.match(server,/Chapter\\s\*\#\?/);
  assert.match(server,/Prologue\\b/);
  assert.match(server,/replaceGoogleDocRange/);
  assert.match(server,/bodyStartIndex/);
  assert.match(server,/await saveChapterSnapshot\(chapter/);
  assert.match(server,/refreshMicheleReadingCopy/);
});

test('Michele companion routes fail gently and admin controls are permission protected',()=>{
  assert.match(server,/app\.get\('\/api\/michele\/book\/continue'/);
  assert.match(server,/app\.post\('\/api\/michele\/book\/converse'/);
  assert.match(server,/micheleFastConversationReply/);
  assert.match(server,/micheleConversationReply/);
  assert.match(server,/micheleFindChapterForMessage/);
  assert.match(server,/micheleEditorialMode/);
  assert.match(server,/what do you think/);
  assert.match(server,/your take/);
  assert.match(server,/micheleDeterministicChapterThoughts/);
  assert.match(server,/This chapter should not be treated like raw material anymore/);
  assert.match(server,/micheleModeSections/);
  assert.match(server,/michele_chapter_analysis/);
  assert.match(server,/all of \(it\|that\|the above\)/);
  assert.match(server,/latestMicheleCompletedChapter/);
  assert.match(server,/listMicheleStoredChaptersForConversation/);
  assert.match(server,/nextMicheleChapterAfter/);
  assert.match(server,/markMicheleChapterProgress/);
  assert.match(server,/lastCompletedChapter/);
  assert.match(server,/What would you like to work on next\?/);
  assert.match(server,/micheleLayeredEditorialFrameworkText/);
  assert.match(server,/micheleInformedChapterQuestion/);
  assert.match(server,/micheleChapterContextSummary/);
  assert.match(server,/micheleChapterShortSummary/);
  assert.match(server,/micheleChapterEditorialSnapshot/);
  assert.match(server,/micheleWordSignals/);
  assert.match(server,/micheleChapterSpecificSignals/);
  assert.match(server,/micheleQuestionSafeSignal/);
  assert.match(server,/elite dating service/);
  assert.match(server,/grown-up fairy tale/);
  assert.match(server,/safeMicheleChapter/);
  assert.match(server,/chapter:safeMicheleChapter\(chapter\)/);
  assert.match(server,/micheleDefaultStrengths/);
  assert.match(server,/micheleDefaultOpportunities/);
  assert.match(server,/micheleSummaryFieldUnsafe/);
  assert.match(server,/micheleBulletsAreSpecific/);
  assert.match(server,/Safe chapter signals:/);
  assert.match(server,/chapterSummary must be 1-2 short sentences/);
  assert.match(server,/strengths must contain exactly 3 bullets/);
  assert.match(server,/opportunities must contain exactly 3 bullets/);
  assert.match(server,/Never return the whole chapter text in any field/);
  assert.match(server,/internalChapterContextSummary/);
  assert.match(server,/Do not ask Michele to choose between humor, scene building, emotional truth, transitions, and reader takeaway/);
  assert.match(server,/Apply Michele’s editorial layering framework by default/);
  assert.match(server,/app\.post\('\/api\/michele\/book\/draft'/);
  assert.match(server,/micheleBookDraftResponse/);
  assert.match(server,/draft_ready/);
  assert.match(server,/micheleBookSessionTurn/);
  assert.match(server,/getOrCreateMicheleBookSession/);
  assert.match(server,/appendMicheleBookTurn/);
  assert.match(server,/michelePlanBookConversationTurn/);
  assert.match(server,/editorialMove/);
  assert.match(server,/reflect, challenge, explore, or write/);
  assert.match(server,/Do not over-interview/);
  assert.match(server,/likelyReady/);
  assert.match(server,/why her answer is useful/);
  assert.match(server,/how that answer will shape the edit/);
  assert.match(server,/That helps because/);
  assert.match(server,/I have enough to shape this now/);
  assert.match(server,/metadata:\{editorialMove:planned\.editorialMove/);
  assert.match(server,/book_conversation_sessions_lookup_idx/);
  assert.match(server,/book_conversation_turns_session_idx/);
  assert.match(server,/app\.post\('\/api\/michele\/book\/session\/turn'/);
  assert.match(server,/getRewriteJobById/);
  assert.match(server,/Draft revision was not found/);
  assert.match(server,/getMicheleStoredChapterForConversation/);
  assert.match(server,/In Interview mode, reply with ONLY the next question/);
  assert.match(server,/micheleMessageRequestsEditorialAnswer/);
  assert.match(server,/micheleConversationTextLooksLikeManuscript/);
  assert.match(server,/Never return rewritten manuscript prose in this conversation route/);
  assert.match(server,/Michele answered:/);
  assert.match(server,/Do not include chapter labels, status updates, “Direction captured,” “Use this as the rewrite direction,” or “Nothing has changed.”/);
  assert.doesNotMatch(server,/reply:`\$\{label\}\\n\\nDirection captured/);
  assert.match(server,/Read Chapter 2 and give me your thoughts/);
  assert.match(server,/Overview, Strengths, Opportunities, Emotional Impact, Reader Confusion Risks, Editorial Recommendations, Proofreading Notes/);
  assert.match(server,/Spelling Errors, Grammar Issues, Punctuation Issues, Repetition, Awkward Phrasing, Suggested Corrections/);
  assert.match(server,/Summary, Major Events, Emotional Arc, Themes, Lessons, Key Takeaways/);
  assert.match(server,/app\.post\('\/api\/michele\/book\/respond'/);
  assert.match(server,/app\.post\('\/api\/michele\/book\/admin\/import-edits'/);
  assert.match(server,/gentleBookError/);
  assert.match(server,/VAL’s writing brain is not connected yet/);
  assert.match(server,/platformKeyFallbackAllowed\('openai'\)/);
  assert.match(server,/VAL_REQUIRE_TENANT_OPENAI_KEY/);
  assert.match(server,/tenantApiKeyLooksValid/);
  assert.match(server,/That does not look like a valid/);
  assert.match(server,/ignoring invalid tenant vault key/);
  assert.match(server,/Stored key does not match expected provider key format/);
  assert.match(server,/micheleReplyRepeatsPriorQuestion/);
  assert.match(server,/micheleNextFallbackQuestion\(chapter,userMessage,conversation\)/);
  assert.match(server,/app\.get\('\/api\/michele\/book\/admin',requirePermission\('settings:manage'\)/);
  assert.match(server,/app\.post\('\/api\/michele\/book\/admin\/restore',requirePermission\('settings:manage'\)/);
  assert.match(server,/config:cfg/);
  assert.match(server,/writeAccessLikely:true,mutated:false/);
  assert.match(server,/Snapshot has no manuscript text to restore/);
  assert.match(server,/coalesce\(length\(trim\(full_text\)\),0\)>0/);
});

test('Michele workflow can use imported prior editor notes from VAL memory',()=>{
  assert.match(server,/function micheleImportedNoteScore/);
  assert.match(server,/async function listMicheleImportedEditorNotes/);
  assert.match(server,/book_editor_notes_import/);
  assert.match(server,/imported_prior_editor_notes/);
  assert.match(server,/listMicheleEditorNotes\(chapter\.id,chapter\)/);
});

test('Michele dashboard exposes one calm Continue My Book workflow',()=>{
  assert.match(dashboard,/Continue My Book/);
  assert.match(dashboard,/openMicheleBookCompanion/);
  assert.match(server,/micheleChapterSpecificQuestion/);
  assert.match(server,/Do not use the vague phrase "What feels right to you\?"/);
  assert.match(dashboard,/michele-book-mini-list/);
  assert.match(dashboard,/Message with VAL/);
  assert.doesNotMatch(dashboard,/Talk with VAL/);
  assert.match(dashboard,/micheleBookChapterSelect/);
  assert.match(dashboard,/micheleBookModeSelect/);
  assert.match(dashboard,/Chapter Overview Mode/);
  assert.match(dashboard,/Proofreading Mode/);
  assert.match(dashboard,/micheleBookChapterLabel/);
  assert.match(dashboard,/selectMicheleBookChapter/);
  assert.match(dashboard,/Rewrite Chapter/);
  assert.match(dashboard,/writeMicheleChapterDirectly/);
  assert.match(dashboard,/micheleBookSendRewrite\(payload\)/);
  assert.match(dashboard,/renderMicheleDraftPreview/);
  assert.match(dashboard,/Review the revised version/);
  assert.match(dashboard,/Keep & Write to Fresh Manuscript/);
  assert.match(dashboard,/Adjust Draft/);
  assert.match(dashboard,/Continue Conversation/);
  assert.match(dashboard,/approveMicheleDraftRevision/);
  assert.match(dashboard,/adjustMicheleDraftRevision/);
  assert.match(dashboard,/readonly/);
  assert.match(dashboard,/fresh manuscript document/);
  assert.match(dashboard,/micheleBookConversationInstruction/);
  assert.match(dashboard,/renderMichelePlacementPrompt/);
  assert.match(dashboard,/continueMicheleBookRewriteWithPlacement/);
  assert.match(dashboard,/window\._michelePendingRewrite/);
  assert.match(dashboard,/payload\.placement=placement/);
  assert.match(dashboard,/api\/michele\/book\/session\/turn/);
  assert.match(dashboard,/window\._micheleBookSessionId/);
  assert.match(dashboard,/window\._micheleBookSessionState/);
  assert.match(dashboard,/Last completed:/);
  assert.match(dashboard,/micheleBookChapterLabel\(last\)/);
  assert.match(dashboard,/Chapter summary/);
  assert.match(dashboard,/3 things working/);
  assert.match(dashboard,/3 things to improve/);
  assert.doesNotMatch(dashboard,/Question for Michele/);
  assert.match(dashboard,/micheleBookControlCardHtml/);
  assert.match(dashboard,/Voice Co-Work/);
  assert.match(dashboard,/Pause/);
  assert.match(dashboard,/Stop/);
  assert.match(dashboard,/michele-book-compact-chat/);
  assert.match(dashboard,/VAL will listen quietly unless Michele says/);
  assert.match(dashboard,/clampMicheleBookText/);
  assert.match(dashboard,/scrubMicheleBookClientState/);
  assert.match(dashboard,/delete copy\.currentText/);
  assert.match(dashboard,/safeMicheleBookDisplayText/);
  assert.match(dashboard,/safeMicheleBookChapterTitle/);
  assert.match(dashboard,/micheleLooksLikeRawChapterText/);
  assert.match(dashboard,/The manuscript text is hidden here/);
  assert.match(dashboard,/docSafe\(title\)/);
  assert.match(dashboard,/chapter transitions, voice consistency, emotional arc, humor/);
  assert.doesNotMatch(dashboard,/sentConversation/);
  assert.match(dashboard,/Reading the selected chapter and preparing a real response/);
  assert.match(dashboard,/continuous=true/);
  assert.match(dashboard,/interimResults=true/);
  assert.match(dashboard,/micheleVoicePanelHtml/);
  assert.match(dashboard,/michele-voice-floating/);
  assert.match(dashboard,/Start Voice Session/);
  assert.match(dashboard,/toggleMicheleVoiceSession/);
  assert.match(dashboard,/startMicheleVoiceSession/);
  assert.match(dashboard,/pauseMicheleVoiceSession/);
  assert.match(dashboard,/endMicheleVoiceSession/);
  assert.match(dashboard,/setMicheleVoiceSessionState/);
  assert.match(dashboard,/Interrupted\. Listening now\./);
  assert.match(dashboard,/Voice session ended/);
  assert.match(dashboard,/preloadSpeech\(prompt\)/);
  assert.match(dashboard,/voiceAudioCache/);
  assert.match(dashboard,/fetchDeepgramTtsBlob/);
  assert.match(dashboard,/onDone\(\)/);
  assert.match(dashboard,/finishMicheleBookVoiceListening/);
  assert.match(dashboard,/scheduleMicheleBookVoiceQuietSubmit/);
  assert.match(dashboard,/micheleVoiceTextAsksVal/);
  assert.match(dashboard,/if\(!addressesVal\)return false/);
  assert.match(dashboard,/captureMicheleBookVoiceNote/);
  assert.match(dashboard,/api\/michele\/book\/session\/capture/);
  assert.match(server,/micheleBookSessionCapture/);
  assert.match(server,/micheleMessageWantsToKeepTalking/);
  assert.match(server,/micheleMessageExplicitlyAsksToWrite/);
  assert.match(dashboard,/window\._micheleBookVoiceFinalText/);
  assert.match(dashboard,/window\._micheleBookVoiceInterimText/);
  assert.match(dashboard,/finishMicheleBookVoiceListening\(\);/);
  assert.doesNotMatch(dashboard,/box\.value=\[window\._micheleBookVoiceFinalText,interim\]/);
  assert.match(dashboard,/voiceText:text/);
  assert.match(dashboard,/voiceMode:!!opts\.fromVoice/);
  assert.match(dashboard,/speak\(data\.reply\|\|'',null,function\(\)\{if\(window\._micheleBookVoiceSession&&window\._micheleBookVoiceSession\.active\)startMicheleBookVoiceListening\(\);\}\)/);
  assert.match(dashboard,/stopMicheleVoiceForDrafting/);
  assert.match(dashboard,/Voice paused while VAL prepares the draft/);
  assert.match(dashboard,/silentUser:true/);
  assert.match(dashboard,/turns\.filter\(function\(turn\)\{return !turn\.hidden;\}\)/);
  assert.match(dashboard,/speak\(data\.reply/);
  assert.match(dashboard,/askMicheleBookOpeningQuestionThenListen/);
  assert.match(dashboard,/window\._micheleBookOpeningQuestion=prompt/);
  assert.match(dashboard,/I’m listening\. Talk through the chapter naturally/);
  assert.match(dashboard,/speak\(intro,null,function\(\)\{if\(window\._micheleBookVoiceSession&&window\._micheleBookVoiceSession\.active\)startMicheleBookVoiceListening\(\);\}\)/);
  assert.match(dashboard,/function startMicheleBookVoiceListening/);
  assert.match(server,/micheleVoiceSizedReply/);
  assert.match(server,/voiceMode\?micheleVoiceSizedReply\(reply\):reply/);
  assert.match(dashboard,/mode:mode/);
  assert.match(dashboard,/Open the fresh manuscript document/);
  assert.match(dashboard,/Voice is ready when Michele is/);
  assert.match(dashboard,/VAL will listen quietly unless Michele says/);
  assert.match(dashboard,/dictateMicheleBookResponse/);
  assert.match(dashboard,/Done\. Chapter/);
  assert.match(dashboard,/openMicheleBookAdmin/);
  assert.match(dashboard,/Test write verifies the fresh manuscript can be opened without changing it/);
  assert.match(dashboard,/Restore failed: /);
  assert.doesNotMatch(dashboard,/apiFetch\(PROXY\+'\/api\/michele\/book\/[^']+'[^)]*\)\.then\(function\(r\)\{return r\.json\(\);\}\)/);
  assert.match(dashboard,/chapter\.chapterTitle\|\|chapter\.chapter_title\|\|chapter\.title/);
  assert.match(dashboard,/api\/michele\/book\/continue',\{cache:'no-store'\}/);
});
