'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');
const dashboard=fs.readFileSync(path.join(__dirname,'..','dashboard.html'),'utf8');
const commandCenter=fs.readFileSync(path.join(__dirname,'..','command-center.js'),'utf8');

test('Teach VAL commit promotes onboarding into core memory and evidence',()=>{
  assert.match(server,/async function promoteTeachValOnboardingToCoreMemory/);
  assert.match(server,/await saveMemoryItem\(\{/);
  assert.match(server,/kind:`teach_val_/);
  assert.match(server,/sourceType:'teach_val_onboarding'/);
  assert.match(server,/await saveEvidenceItem\(\{/);
  assert.match(server,/runObservationEngine\(evidence,\{candidates:teachValEvidenceCandidates\(included\),replace:true\}\)/);
  assert.match(server,/promotion=await promoteTeachValOnboardingToCoreMemory\(\{session,imports,items:included,payload\}\)/);
  assert.match(server,/res\.json\(\{ok:true,payload,webhook,promotion,operationalInsights/);
});

test('Teach VAL onboarding categories map into universal observation types',()=>{
  for(const type of ['relationship_signal','risk','preference','opportunity','need','idea']){
    assert.match(server,new RegExp(`'${type}'`));
  }
  assert.match(server,/function teachValObservationType/);
  assert.match(server,/function teachValEvidenceCandidates/);
  assert.match(server,/function teachValMemoryImportance/);
});

test('Teach VAL can scan connected sources into VAL OS insights without changing behavior',()=>{
  assert.match(server,/const VAL_OS_FUNCTIONS = \['email','calendar','tasks','crm','relationships','voice','documents','transcripts','memory'\]/);
  assert.match(server,/const VAL_OS_LAYERS = \['observation','understanding','recommendation','approved_behavior','execution','reflection'\]/);
  assert.match(server,/function connectedSourceInsightPayload/);
  assert.match(server,/async function buildTeachValConnectedSourceInsights/);
  assert.match(server,/app\.get\('\/api\/teach-val\/source-insights'/);
  assert.match(server,/app\.post\('\/api\/teach-val\/onboarding\/:id\/source-insights'/);
  assert.match(server,/category:'connected_source_insights'/);
  assert.match(server,/requiresApproval:true/);
  assert.match(server,/Observe first, recommend second, require approval before behavior changes\./);
});

test('Teach VAL onboarding operationalizes agreements without acting externally',()=>{
  assert.match(server,/function teachValOnboardingOperationalInsights/);
  assert.match(server,/function teachValOperationalRuleDraft/);
  assert.match(server,/category:'onboarding_operational_context'/);
  assert.match(server,/working_agreement_review_first/);
  assert.match(server,/linkedin_visibility_review_first/);
  assert.match(server,/never_auto_publish:true/);
  assert.match(server,/require_review_before_external_action:true/);
  assert.match(server,/require_review_before_durable_memory:true/);
  assert.match(server,/externalActionsLocked:true/);
  assert.match(server,/reviewRequired:true/);
  assert.match(server,/noExternalAction:true/);
  assert.match(server,/operationalInsights=teachValOnboardingOperationalInsights\(\{session,items:included\}\)/);
  assert.match(server,/operationalInsightCount:operationalInsights\.length/);
  assert.match(server,/\['connected_source_insights','onboarding_operational_context'\]\.includes\(i\.category\)/);
  assert.match(server,/draftBehaviors=insights\.filter\(item=>item\.data\?\.ruleDraft\)/);
});

test('Teach VAL onboarding reflection routes new onboarding categories into the system',()=>{
  assert.match(server,/workingAgreements=cat\(\/working_agreements\/\)/);
  assert.match(server,/linkedinStrategy=cat\(\/linkedin_strategy\/\)/);
  assert.match(server,/supportCircle=cat\(\/support_circle\/\)/);
  assert.match(server,/documentExamples=cat\(\/documents_and_examples\/\)/);
  assert.match(server,/Working agreements are waiting in VAL OS review/);
  assert.match(server,/LinkedIn strategy is held as draft-only visibility context/);
  assert.match(server,/Support circle context added/);
  assert.match(server,/Document and example references added/);
  assert.match(server,/working agreement.*ready for VAL OS review/);
  assert.match(server,/LinkedIn strategy ready for draft-only review/);
  assert.match(server,/Support circle ready to connect to relationships/);
  assert.match(server,/Document examples ready to organize as references/);
});

test('Teach VAL UI exposes connected inbox and calendar insights for review',()=>{
  assert.match(dashboard,/var teachValSourceInsights=null/);
  assert.match(dashboard,/function teachValScanSources/);
  assert.match(dashboard,/function teachValSourceInsightsHtml/);
  assert.match(dashboard,/function teachValImportSourceInsights/);
  assert.match(dashboard,/Connected Source Insights/);
  assert.match(dashboard,/Scan Email & Calendar/);
  assert.match(dashboard,/Import To Teach VAL/);
  assert.match(dashboard,/Observe, recommend, approve, then execute/);
});

test('My VAL OS exposes rule approval with auditability and review-first execution',()=>{
  assert.match(server,/app\.get\('\/api\/val\/os'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/readiness\/check'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/external-action-packets\/:id\/update'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/external-action-packets\/:id\/approve'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/rules'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/review-queue\/run'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/calendar-approvals\/run'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/calendar-approvals\/:id\/decision'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/calendar-approvals\/:id\/action-draft'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/calendar-approvals\/:id\/execution-preview'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/calendar-approvals\/:id\/permission-slip'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/calendar-approvals\/:id\/execution-rehearsal'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/calendar-approvals\/:id\/final-confirmation-packet'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/calendar-approvals\/:id\/final-confirmation-packet\/review'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/calendar-approvals\/:id\/final-confirmation-packet\/internal-task'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/calendar-approvals\/:id\/clarification'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/review-queue\/:id\/decision'/);
  assert.match(server,/app\.post\('\/api\/val\/os\/learning\/:id\/decision'/);
  assert.match(server,/function buildValOsState/);
  assert.match(server,/function buildValOsReflection/);
  assert.match(server,/function buildValOsTrustLedger/);
  assert.match(server,/function buildValOsSafetySummary/);
  assert.match(server,/function buildValOsActionRegistry/);
  assert.match(server,/function buildValOsExecutorStatus/);
  assert.match(server,/function normalizeValOsExternalActionPacket/);
  assert.match(server,/function buildGhlExternalActionPacket/);
  assert.match(server,/CRM action packet from Co-Work/);
  assert.match(server,/capability:'ghl_mcp_cowork_action_packet'/);
  assert.match(server,/function updateValOsExternalActionPacket/);
  assert.match(server,/function approveValOsExternalActionPacket/);
  assert.match(server,/async function buildValOsExternalActionReadiness/);
  assert.match(server,/function saveValOsRule/);
  assert.match(server,/function saveValOsLearningDecision/);
  assert.match(server,/function normalizeValOsCalendarApproval/);
  assert.match(server,/function normalizeValOsCalendarPermissionSlip/);
  assert.match(server,/function normalizeValOsCalendarExecutionRehearsal/);
  assert.match(server,/function normalizeValOsCalendarFinalConfirmationPacket/);
  assert.match(server,/function normalizeValOsCalendarInternalActionReceipt/);
  assert.match(server,/function normalizeValOsCalendarExecutionPreview/);
  assert.match(server,/function normalizeValOsCalendarActionDraft/);
  assert.match(server,/function loadValOsCalendarApprovalCandidateEvents/);
  assert.match(server,/function valOsCalendarClarificationQuestions/);
  assert.match(server,/function runValOsCalendarApprovalScan/);
  assert.match(server,/function prepareValOsCalendarActionDraft/);
  assert.match(server,/function prepareValOsCalendarExecutionPreview/);
  assert.match(server,/function buildValOsCalendarExecutionPreview/);
  assert.match(server,/function buildValOsCalendarPermissionSlip/);
  assert.match(server,/function saveValOsCalendarPermissionSlip/);
  assert.match(server,/function buildValOsCalendarExecutionRehearsal/);
  assert.match(server,/function saveValOsCalendarExecutionRehearsal/);
  assert.match(server,/function buildValOsCalendarFinalConfirmationPacket/);
  assert.match(server,/function saveValOsCalendarFinalConfirmationPacket/);
  assert.match(server,/function reviewValOsCalendarFinalConfirmationPacket/);
  assert.match(server,/function createValOsCalendarFinalPacketInternalTask/);
  assert.match(server,/function saveValOsCalendarClarification/);
  assert.match(server,/function buildValOsCalendarActionDraft/);
  assert.match(server,/function decideValOsCalendarApproval/);
  assert.match(server,/function valOsLearningReviewItems/);
  assert.match(server,/function decideValOsLearningItem/);
  assert.match(server,/function runValOsReviewQueue/);
  assert.match(server,/function decideValOsReviewItem/);
  assert.match(server,/function valOsFeedbackBehaviorCandidates/);
  assert.match(server,/valOsReviewQueue/);
  assert.match(server,/valOsCalendarApprovals/);
  assert.match(server,/VAL_OS_CALENDAR_ACTION_LEVELS/);
  assert.match(server,/approved_not_executed/);
  assert.match(server,/executionAvailable:false/);
  assert.match(server,/calendarNeedsApproval/);
  assert.match(server,/calendarActionDrafts/);
  assert.match(server,/calendarExecutionPreviews/);
  assert.match(server,/calendarClarifications/);
  assert.match(server,/trustLedger/);
  assert.match(server,/safetySummary/);
  assert.match(server,/actionRegistry/);
  assert.match(server,/executorStatus/);
  assert.match(server,/valOsExternalActionPackets/);
  assert.match(server,/externalActionPacket/);
  assert.match(server,/ghlMcpCoworkActionPacket:true/);
  assert.match(server,/noExternalAction:true/);
  assert.match(server,/Approve & Do It/);
  assert.match(server,/external_action_packet_updated/);
  assert.match(server,/val_os_external_action_packet_updated/);
  assert.match(server,/external_action_packet_executed/);
  assert.match(server,/val_os_external_action_packet_executed/);
  assert.match(server,/externalActionReadiness/);
  assert.match(server,/create_internal_task/);
  assert.match(server,/create_internal_draft/);
  assert.match(server,/prepare_meeting_prep_note/);
  assert.match(server,/draft_email_reply/);
  assert.match(server,/update_calendar_event/);
  assert.match(server,/provider_locked/);
  assert.match(server,/supervised_internal/);
  assert.match(server,/Provider write executor is intentionally not built/);
  assert.match(server,/External provider actions remain locked/);
  assert.match(server,/External Action Readiness Gate/);
  assert.match(server,/Connection check only/);
  assert.match(server,/readyForSupervisedExecution:false/);
  assert.match(server,/executionAvailable:false/);
  assert.match(server,/writeLocked:true/);
  assert.match(server,/external_action_readiness_check/);
  assert.match(server,/val_os_external_action_readiness_check/);
  assert.match(server,/currentStage:'Execution preview only'/);
  assert.match(server,/Actual external calendar execution is intentionally not built/);
  assert.match(server,/Observe > Proposal > Clarification > Draft > Execution Preview > Explicit Approval > Actual execution/);
  assert.match(server,/executionPreview/);
  assert.match(server,/permissionSlip/);
  assert.match(server,/executionRehearsal/);
  assert.match(server,/finalConfirmationPacket/);
  assert.match(server,/internalActionReceipt/);
  assert.match(server,/calendar_permission_slip_recorded/);
  assert.match(server,/val_os_calendar_permission_slip_recorded/);
  assert.match(server,/calendar_execution_rehearsal_completed/);
  assert.match(server,/val_os_calendar_execution_rehearsal_completed/);
  assert.match(server,/calendar_final_confirmation_packet_prepared/);
  assert.match(server,/val_os_calendar_final_confirmation_packet_prepared/);
  assert.match(server,/calendar_final_confirmation_packet_reviewed/);
  assert.match(server,/val_os_calendar_final_confirmation_packet_reviewed/);
  assert.match(server,/calendar_final_packet_internal_task_created/);
  assert.match(server,/val_os_calendar_final_packet_internal_task_created/);
  assert.match(server,/intent_recorded_not_executable/);
  assert.match(server,/final_confirmation_review_only/);
  assert.match(server,/reviewDecision/);
  assert.match(server,/reviewNote/);
  assert.match(server,/looks_right/);
  assert.match(server,/needs_revision/);
  assert.match(server,/simulated_only/);
  assert.match(server,/simulatedOnly:true/);
  assert.match(server,/liveExecutionLocked:true/);
  assert.match(server,/finalConfirmationRecorded:false/);
  assert.match(server,/internalOnly:true/);
  assert.match(server,/providerTouched:false/);
  assert.match(server,/Internal VAL task created/);
  assert.match(server,/No live request was sent/);
  assert.match(server,/readyForExecutor:false/);
  assert.match(server,/requiresFinalConfirmation:true/);
  assert.match(server,/Permission slip records one-action intent only/);
  assert.match(server,/hasNotHappenedYet:true/);
  assert.match(server,/clarificationStatus/);
  assert.match(server,/clarificationQuestions/);
  assert.match(server,/valOsLearningDecisions/);
  assert.match(server,/learningReview/);
  assert.match(server,/learningNeedsReview/);
  assert.match(server,/externalActionsTaken/);
  assert.match(server,/nextTrustMove/);
  assert.match(server,/feedbackBehaviors/);
  assert.match(server,/review_feedback/);
  assert.match(server,/reduce_false_positives/);
  assert.match(server,/executionMode:'review_first'/);
  assert.match(server,/approvalRequired:true/);
  assert.match(server,/externalActionTaken:false/);
  assert.match(server,/reviewOnly:true/);
  assert.match(server,/saveInternalDraft\(\{/);
  assert.match(server,/await saveTask\(task\)/);
  assert.match(server,/saveValOsAudit/);
  assert.match(dashboard,/data-view="val_os"/);
  assert.match(dashboard,/function openValOsPage/);
  assert.match(dashboard,/function valOsApproveRule/);
  assert.match(dashboard,/function valOsSkipRule/);
  assert.match(dashboard,/function valOsLearningReviewHtml/);
  assert.match(dashboard,/function valOsReflectionHtml/);
  assert.match(dashboard,/function valOsTrustLedgerHtml/);
  assert.match(dashboard,/function valOsSafetySummaryHtml/);
  assert.match(dashboard,/function valOsExecutorStatusHtml/);
  assert.match(dashboard,/function valOsExternalActionReadinessHtml/);
  assert.match(dashboard,/function renderExternalActionPacket/);
  assert.match(dashboard,/function saveExternalActionPacketTweaks/);
  assert.match(dashboard,/function approveExternalActionPacket/);
  assert.match(dashboard,/function cancelExternalActionPacket/);
  assert.match(dashboard,/function valOsReflectionList/);
  assert.match(dashboard,/function valOsCalendarApprovalHtml/);
  assert.match(dashboard,/function valOsRunCalendarPregame/);
  assert.match(dashboard,/function valOsRunReadinessCheck/);
  assert.match(dashboard,/function valOsCalendarDecision/);
  assert.match(dashboard,/function valOsPrepareCalendarActionDraft/);
  assert.match(dashboard,/function valOsPrepareExecutionPreview/);
  assert.match(dashboard,/function valOsRecordPermissionSlip/);
  assert.match(dashboard,/function valOsRunExecutionRehearsal/);
  assert.match(dashboard,/function valOsPrepareFinalConfirmationPacket/);
  assert.match(dashboard,/function valOsReviewFinalConfirmationPacket/);
  assert.match(dashboard,/function valOsCreateFinalPacketInternalTask/);
  assert.match(dashboard,/function valOsOpenExecutionPreviewTweak/);
  assert.match(dashboard,/function valOsSubmitExecutionPreviewTweak/);
  assert.match(dashboard,/function valOsSubmitCalendarClarification/);
  assert.match(dashboard,/function valOsSetCalendarClarificationAnswer/);
  assert.match(dashboard,/function valOsOpenCalendarTweak/);
  assert.match(dashboard,/function valOsSubmitCalendarTweak/);
  assert.match(dashboard,/function valOsOpenCalendarDraftEdit/);
  assert.match(dashboard,/function valOsSubmitCalendarDraftTweak/);
  assert.match(dashboard,/function valOsLearningDecision/);
  assert.match(dashboard,/function valOsOpenLearningCorrection/);
  assert.match(dashboard,/function valOsSubmitLearningCorrection/);
  assert.match(dashboard,/function valOsReviewQueueHtml/);
  assert.match(dashboard,/function valOsRunReviewQueue/);
  assert.match(dashboard,/function valOsReviewDecision/);
  assert.match(dashboard,/function valOsOpenReviewFeedback/);
  assert.match(dashboard,/function valOsSubmitReviewFeedback/);
  assert.match(dashboard,/function valOsOpenDraftReview/);
  assert.match(dashboard,/Review Behavior Candidate/);
  assert.match(dashboard,/Learning Review/);
  assert.match(dashboard,/Reflection Panel/);
  assert.match(dashboard,/Safety Summary/);
  assert.match(dashboard,/What VAL can do now, what it cannot do yet/);
  assert.match(dashboard,/Action Registry & Executor Shell/);
  assert.match(dashboard,/Registered Actions/);
  assert.match(dashboard,/Safety Questions/);
  assert.match(dashboard,/Operating Rules/);
  assert.match(dashboard,/enabled actions/);
  assert.match(dashboard,/locked actions/);
  assert.match(dashboard,/internal receipts/);
  assert.match(dashboard,/Executor Shell:/);
  assert.match(dashboard,/External Action Readiness Gate/);
  assert.match(dashboard,/External Action Approval/);
  assert.match(dashboard,/One approval required/);
  assert.match(dashboard,/Review and tweak details before approving/);
  assert.match(dashboard,/Saving tweaks updates the actual action VAL will send/);
  assert.match(dashboard,/Save Tweaks/);
  assert.match(dashboard,/Tweaks saved\. Review the updated action/);
  assert.match(dashboard,/Approve & Do It/);
  assert.match(dashboard,/External Action Receipt/);
  assert.match(dashboard,/External action completed and receipt recorded/);
  assert.match(dashboard,/Connection Check Only/);
  assert.match(dashboard,/Run Connection Check Only/);
  assert.match(dashboard,/Writes locked/);
  assert.match(dashboard,/external writes/);
  assert.match(dashboard,/Approval packet must include:/);
  assert.match(dashboard,/No external action taken/);
  assert.match(dashboard,/External writes remain locked/);
  assert.match(dashboard,/does not change Google, Outlook, CRM/);
  assert.match(dashboard,/VAL can currently:/);
  assert.match(dashboard,/VAL cannot do yet:/);
  assert.match(dashboard,/current stage/);
  assert.match(dashboard,/Execution preview only/);
  assert.match(dashboard,/Actual external calendar execution is intentionally not built/);
  assert.match(dashboard,/Observe > Proposal > Clarification > Draft > Execution Preview > Explicit Approval > Actual execution/);
  assert.match(dashboard,/What changed, what stayed review-only/);
  assert.match(dashboard,/external actions/);
  assert.match(dashboard,/Accountability:/);
  assert.match(dashboard,/Next trust move:/);
  assert.match(dashboard,/Approve or tweak what VAL thinks it learned/);
  assert.match(dashboard,/names, schools, family details/);
  assert.match(dashboard,/Confirm/);
  assert.match(dashboard,/Tweak/);
  assert.match(dashboard,/Save Tweak/);
  assert.match(dashboard,/Calendar Approval Queue/);
  assert.match(dashboard,/Trust Ledger/);
  assert.match(dashboard,/Trust boundary held/);
  assert.match(dashboard,/Run Calendar Pregame/);
  assert.match(dashboard,/Current Event/);
  assert.match(dashboard,/Proposed Change/);
  assert.match(dashboard,/Calendar Action Draft/);
  assert.match(dashboard,/Execution Preview/);
  assert.match(dashboard,/Prepare Execution Preview/);
  assert.match(dashboard,/Permission Slip/);
  assert.match(dashboard,/Record Permission Slip/);
  assert.match(dashboard,/Simulated Execution Rehearsal/);
  assert.match(dashboard,/Run Simulated Rehearsal/);
  assert.match(dashboard,/Dry run only/);
  assert.match(dashboard,/Simulated request:/);
  assert.match(dashboard,/Receipt preview:/);
  assert.match(dashboard,/No provider request was sent/);
  assert.match(dashboard,/Final Confirmation Packet/);
  assert.match(dashboard,/Prepare Final Confirmation Packet/);
  assert.match(dashboard,/Last look only/);
  assert.match(dashboard,/Live execution is still locked/);
  assert.match(dashboard,/Action summary:/);
  assert.match(dashboard,/Outside system:/);
  assert.match(dashboard,/Permission history:/);
  assert.match(dashboard,/What will not happen:/);
  assert.match(dashboard,/Your choices:/);
  assert.match(dashboard,/Optional trust note/);
  assert.match(dashboard,/Looks Right/);
  assert.match(dashboard,/Needs Revision/);
  assert.match(dashboard,/Your packet review:/);
  assert.match(dashboard,/Trust note:/);
  assert.match(dashboard,/Final confirmation packet review saved/);
  assert.match(dashboard,/Revise Preview/);
  assert.match(dashboard,/Cancel/);
  assert.match(dashboard,/Final confirmation packet prepared for review only/);
  assert.match(dashboard,/Create Internal Task/);
  assert.match(dashboard,/Internal Action Receipt/);
  assert.match(dashboard,/Internal VAL task created/);
  assert.match(dashboard,/This happened inside VAL only/);
  assert.match(dashboard,/No provider, email, calendar, CRM, contact system, invite, message, or reschedule was touched/);
  assert.match(dashboard,/Intent recorded, not executable/);
  assert.match(dashboard,/not a final execution command/);
  assert.match(dashboard,/Final confirmation still required/);
  assert.match(dashboard,/Permission slip recorded for this preview only/);
  assert.match(dashboard,/This has not happened yet/);
  assert.match(dashboard,/Provider:/);
  assert.match(dashboard,/Risk level:/);
  assert.match(dashboard,/Rollback note:/);
  assert.match(dashboard,/Record Permission Slip/);
  assert.match(dashboard,/Do Not Do This/);
  assert.match(dashboard,/Save Preview Tweak/);
  assert.match(dashboard,/This preview did not update Google, Outlook, invite attendees, or send messages/);
  assert.match(dashboard,/Needs Human Clarification/);
  assert.match(dashboard,/VAL is not assuming/);
  assert.match(dashboard,/Save Clarification/);
  assert.match(dashboard,/Clarification saved/);
  assert.match(dashboard,/Prepare Draft Only/);
  assert.match(dashboard,/Draft only:/);
  assert.match(dashboard,/Tweak Draft/);
  assert.match(dashboard,/Save Draft Tweak/);
  assert.match(dashboard,/This draft did not update Google, Outlook, invite attendees, or send messages/);
  assert.match(dashboard,/Affected people/);
  assert.match(dashboard,/Execution is not available/);
  assert.match(dashboard,/No calendar event was changed/);
  assert.match(dashboard,/VAL did not reschedule, invite, send, delete, or change any calendar/);
  assert.match(dashboard,/Review Queue/);
  assert.match(dashboard,/Run Review Scan/);
  assert.match(dashboard,/Looks Right/);
  assert.match(dashboard,/Not Useful/);
  assert.match(dashboard,/Create Internal Draft/);
  assert.match(dashboard,/Create Internal Task/);
  assert.match(dashboard,/Adjust Behavior/);
  assert.match(dashboard,/Feedback learning:/);
  assert.match(dashboard,/refinements/);
  assert.match(dashboard,/No external action taken/);
  assert.match(dashboard,/Approve Edited Behavior/);
  assert.match(dashboard,/This allows VAL to:/);
  assert.match(dashboard,/This does not allow VAL to:/);
  assert.match(dashboard,/My VAL OS/);
  assert.match(commandCenter,/id:'val_os',icon:'system',label:'My VAL OS',group:'settings'/);
  assert.match(commandCenter,/val_os:'openValOsPage'/);
  assert.match(dashboard,/Trust boundary:/);
  assert.match(dashboard,/Approval required/);
  assert.match(dashboard,/Behavior Candidates/);
  assert.match(dashboard,/VAL may prepare and suggest/);
  assert.match(dashboard,/Why VAL can use it/);
  assert.match(dashboard,/Why VAL surfaced this/);
  assert.match(dashboard,/Your decision:/);
  assert.match(dashboard,/valOsCount\(rule\.timesExecuted\)/);
  assert.match(dashboard,/valOsCount\(c\.beliefs\)/);
  assert.match(dashboard,/valOsCount\(c\.learningNeedsReview\)/);
  assert.match(dashboard,/valOsCount\(c\.reviewQueue\)/);
  assert.match(dashboard,/valOsCount\(c\.calendarNeedsApproval\)/);
  assert.match(dashboard,/valOsCount\(c\.calendarActionDrafts\)/);
  assert.match(dashboard,/valOsCount\(c\.feedbackBehaviors\)/);
  assert.doesNotMatch(dashboard,/Execute Now/);
  assert.match(dashboard,/Final Send Review/);
  assert.match(dashboard,/nothing sends until you click Send Now/);
  assert.doesNotMatch(dashboard,/Update Calendar/);
  assert.doesNotMatch(dashboard,/Reschedule Now/);
  assert.doesNotMatch(dashboard,/Invite Now/);
});

test('VAL OS UI avoids raw internal evidence and rule-engine language',()=>{
  assert.doesNotMatch(dashboard,/JSON\.stringify\(ev\)/);
  assert.doesNotMatch(dashboard,/Rule draft:/);
  assert.doesNotMatch(dashboard,/rule draft is no longer visible/);
  assert.doesNotMatch(dashboard,/Skipped rule draft/);
  assert.doesNotMatch(dashboard,/behavior drafts/);
  assert.match(dashboard,/Behavior candidate:/);
  assert.match(dashboard,/Behavior Candidates/);
  assert.match(dashboard,/That behavior candidate is no longer visible/);
  assert.match(server,/Missing behavior candidate id/);
  assert.match(server,/Skipped behavior candidate/);
});

test('Teach VAL uses ChatGPT context prompts without the voice onboarding step',()=>{
  assert.match(server,/function teachValPublicCard/);
  assert.match(server,/function teachValPublicImport/);
  assert.match(server,/cards:TEACH_VAL_KNOWLEDGE_CARDS\.map\(teachValPublicCard\)/);
  assert.match(server,/witness_meeting_val/);
  assert.match(server,/witness_your_story/);
  assert.match(server,/witness_your_mission/);
  assert.match(server,/witness_never_compromised/);
  assert.match(server,/Do not flatter, diagnose, or promote durable memory automatically/);
  assert.match(server,/state:\{\.\.\.teachValDefaultState\(\),stage:'welcome',mode:requestedMode/);
  assert.match(server,/What are the main workstreams VAL should track for this project\?/);
  assert.match(server,/Project Manager page questions exactly/);
  assert.match(server,/data\.project_manager_import_packet/);
  assert.match(server,/yes_create_project, no_not_project, unsure_ask_user/);
  assert.match(server,/prompt:card\.prompt/);
  assert.doesNotMatch(server,/state\.stage=state\.stage==='welcome'\?'voice_interview'/);
  assert.doesNotMatch(server,/external_ai_imports:imports\.map\(i=>\(\{category:i\.category,prompt_used/);
  assert.match(dashboard,/ChatGPT Context Transfer/);
  assert.match(server,/working_agreements/);
  assert.match(server,/linkedin_strategy/);
  assert.match(server,/support_circle/);
  assert.match(server,/documents_and_examples/);
  assert.match(server,/never auto-publish LinkedIn content/);
  assert.match(server,/operating agreements with VAL/);
  assert.match(server,/Working Agreements/);
  assert.match(server,/LinkedIn Strategy/);
  assert.match(server,/People I Support/);
  assert.match(server,/Documents and Examples/);
  assert.match(dashboard,/You can come back later to add people, projects, working agreements, documents, LinkedIn examples, or changed priorities/);
  assert.match(dashboard,/route them into Relationships, Projects, Documents, Commitments, Leverage, Velocity, and Working Agreements/);
  assert.match(dashboard,/Copy Prompt/);
  assert.match(dashboard,/teachValPromptCopyStatus/);
  assert.match(dashboard,/Copied\. Paste it into ChatGPT or Claude\./);
  assert.match(dashboard,/Prompt copied\./);
  assert.match(dashboard,/Paste Response/);
  assert.match(dashboard,/teach-val-prompt-icon/);
  assert.match(dashboard,/teach-val-prompt-label/);
  assert.match(dashboard,/teach-val-prompt-btn\.active\{background:linear-gradient\(135deg,#5b21d6,#6d28d9\)!important/);
  assert.match(dashboard,/html body \.exec-workspace-modal \.teach-val-stage \.teach-val-prompt-btn\.active/);
  assert.match(dashboard,/teach-val-copy-status/);
  assert.match(dashboard,/teach-val-status-pill/);
  assert.match(dashboard,/footer:'<button class="alert-btn" onclick="closeExecutiveWorkspace/);
  assert.doesNotMatch(dashboard,/Start Voice Interview/);
  assert.doesNotMatch(dashboard,/teachValVoiceStageHtml/);
  assert.doesNotMatch(dashboard,/teach-val-voice-active/);
});

test('Witnessing Session stores Living Executive Graph fields behind conversational prompts',()=>{
  assert.match(server,/const OBSERVATION_MATURITY_STATES = \['noticed','repeated','supported','confirmed','challenged','retired'\]/);
  assert.match(server,/const PARTNERSHIP_PROTOCOL_CARDS/);
  assert.match(server,/function partnershipProtocolCardFor/);
  assert.match(server,/async function observePartnershipProtocolAnswer/);
  assert.match(server,/async function witnessPartnershipProtocolAnswer/);
  assert.match(server,/function fallbackPartnershipProtocolGraph/);
  assert.match(server,/function fallbackPartnershipProtocolWitness/);
  assert.match(server,/function partnershipFallbackFrame/);
  assert.match(server,/Live observation model unavailable\. VAL will not use canned observer frames\./);
  assert.match(server,/return nextCard\.visibleQuestion \|\| ''/);
  assert.match(server,/Live witnessing model unavailable\. VAL will not use canned witnessing responses\./);
  assert.match(server,/let RUNTIME_OPENAI_KEY = ''/);
  assert.match(server,/let RUNTIME_OPENAI_MODEL = ''/);
  assert.match(server,/app\.post\('\/api\/dev\/openai-runtime'/);
  assert.match(server,/app\.post\('\/api\/dev\/openai-runtime\/test'/);
  assert.doesNotMatch(server,/if\(IS_PRODUCTION\) return res\.status\(404\)\.json\(\{ok:false,error:'Not available in production\.'\}\)/);
  assert.match(server,/production:IS_PRODUCTION/);
  assert.match(server,/OpenAI is connected for production Witnessing/);
  assert.match(server,/RUNTIME_OPENAI_KEY \|\| resolveIntegrationSecret\('openai','api_key',OPENAI_KEY\)/);
  assert.match(server,/RUNTIME_OPENAI_MODEL \|\| resolveIntegrationSecret\('openai','preferred_model',OPENAI_CHAT_MODEL\)/);
  assert.doesNotMatch(server,/cardFrames/);
  assert.doesNotMatch(server,/VAL_ALLOW_CANNED_WITNESSING/);
  assert.doesNotMatch(server,/function contextualFallbackQuestion/);
  assert.match(server,/function witnessLinesTooThin/);
  assert.match(server,/function witnessGroundingMatches/);
  assert.match(server,/function priorWitnessLanguage/);
  assert.match(server,/function witnessLinesReusePrior/);
  assert.match(server,/used_language/);
  assert.match(server,/function userFacingWitnessLine/);
  assert.match(server,/VAL_WITNESSING_MASTER_CONSTITUTION/);
  assert.match(server,/The purpose of onboarding is not to collect information/);
  assert.match(server,/questionGoal/);
  assert.match(server,/function composePartnershipProtocolNextQuestion/);
  assert.match(server,/function partnershipIntegrityChainEntry/);
  assert.match(server,/function compactPartnershipEvidenceChain/);
  assert.match(server,/function partnershipCurrentState/);
  assert.match(server,/function partnershipThemeSignals/);
  assert.match(server,/function partnershipOpenLoops/);
  assert.match(server,/function partnershipShiftCandidates/);
  assert.match(server,/integrityChain/);
  assert.match(server,/evidenceChain/);
  assert.match(server,/currentState/);
  assert.match(server,/shift_candidates/);
  assert.match(server,/open_loops/);
  assert.match(server,/V1\.\.V/);
  assert.match(server,/O1\.\.O/);
  assert.match(server,/C1\.\.C/);
  assert.match(server,/previous_answer_variables/);
  assert.match(server,/app\.post\('\/api\/teach-val\/onboarding\/:id\/witnessing-cards\/:cardId\/confirm'/);
  assert.match(server,/source:'user_confirmation'/);
  assert.match(server,/Evidence -> Observation -> Witness -> Confirm|Observe -> Structure -> Witness -> Confirm/);
  assert.match(server,/VAL never responds with reassurance when it can respond with observation/);
  assert.match(server,/A few questions ago/);
  assert.match(server,/Now this sounds like/);
  assert.doesNotMatch(server,/May I tell you what stood out to me/);
  assert.match(server,/Do not reuse prior witness lines or stock sentence shapes/);
  assert.doesNotMatch(server,/You never mentioned your role/);
  assert.doesNotMatch(server,/relationships may not be separate from your work/);
  assert.doesNotMatch(server,/Something about that gives me a place to be curious/);
  assert.doesNotMatch(server,/Something about that makes me curious/);
  assert.match(server,/Imagine you are meeting this person for coffee/);
  assert.match(server,/what a thoughtful human would naturally become curious about/);
  assert.match(server,/curiosity/);
  assert.match(server,/genuine_wonder/);
  assert.match(server,/relational_focus/);
  assert.match(server,/Observer -> Curiosity -> Witness|Witness the single curiosity focus|single curiosity focus/);
  assert.doesNotMatch(server,/earned_belonging/);
  assert.doesNotMatch(server,/earned_rest/);
  assert.doesNotMatch(server,/hope that had to become resilience/);
  assert.doesNotMatch(server,/protecting what you have already earned/);
  for(const category of [
    'witness_support_style',
    'witness_partnership_useful',
    'witness_connect_sources',
    'witness_source_review',
    'witness_key_relationships',
    'witness_documents_templates',
    'witness_import_context',
    'witness_partnership_agreement'
  ]){
    assert.match(server,new RegExp(category));
  }
  assert.match(server,/documents_templates/);
  assert.match(server,/import_context/);
  assert.match(server,/partnership_agreement/);
  assert.match(server,/app\.post\('\/api\/teach-val\/onboarding\/:id\/witnessing-cards\/:cardId'/);
  assert.match(server,/living_executive_graph_v1/);
  assert.match(server,/livingExecutiveGraph:graph/);
  assert.match(server,/protected/);
  assert.match(server,/confidence_source/);
  assert.match(server,/why_this_card_exists_now/);
  assert.match(server,/permanence_profile/);
  assert.match(server,/immediate_consumers/);
  assert.match(server,/future_consumers/);
  assert.match(server,/saveTeachValImport/);
  assert.match(server,/status:'Witnessed'/);
  assert.doesNotMatch(server,/Memory saved/);
});

test('Witnessing accepts concise lines grounded in the current answer without allowing boilerplate',()=>{
  const validator=server.match(/function userFacingWitnessLine[\s\S]*?(?=function fallbackPartnershipProtocolWitness)/)?.[0]||'';
  assert.ok(validator,'Witnessing validation helpers should be available for regression coverage.');
  const context={};
  vm.runInNewContext(`${validator}\nresult={witnessLinesTooThin};`,context);
  const answer='I am first and foremost a mom. After that I use technology to support people\'s visions, capacity, and integrity/accountability.';
  const grounded=[
    'Being a mom comes first, and technology is in service of people\'s visions.',
    'That order makes integrity and accountability part of how VAL should support you.'
  ];
  assert.equal(context.result.witnessLinesTooThin(grounded,answer,{}),false);
  assert.equal(context.result.witnessLinesTooThin(['I hear you, and I will listen carefully.'],answer,{}),true);
});

test('Witnessing Session bounds model work to one responsive conversation turn',()=>{
  const turn=server.match(/async function generatePartnershipProtocolTurn[\s\S]*?\n}\nfunction partnershipGraphItems/)?.[0] || '';
  const route=server.match(/app\.post\('\/api\/teach-val\/onboarding\/:id\/witnessing-cards\/:cardId',[\s\S]*?\n}\);\napp\.post\('\/api\/teach-val\/onboarding\/:id\/witnessing-cards\/:cardId\/confirm'/)?.[0] || '';
  const openAi=server.match(/async function callOpenAIResponses[\s\S]*?\n}\n\nasync function callOpenAIWebResearch/)?.[0] || '';

  assert.match(server,/const VAL_WITNESSING_OBSERVATION_TIMEOUT_MS/);
  assert.match(server,/const VAL_WITNESSING_RESPONSE_TIMEOUT_MS/);
  assert.match(server,/const VAL_WITNESSING_REPAIR_TIMEOUT_MS/);
  assert.match(server,/const VAL_WITNESSING_TURN_TIMEOUT_MS/);
  assert.match(server,/const VAL_WITNESSING_TURN_OUTPUT_TOKENS/);
  assert.match(server,/const VAL_WITNESSING_TURN_RETRY_OUTPUT_TOKENS/);
  assert.match(server,/const VAL_WITNESSING_TURN_RESPONSE_FORMAT/);
  assert.match(openAi,/fetchWithTimeout\('https:\/\/api\.openai\.com\/v1\/responses',options,timeoutMs,'OpenAI response'\)/);
  assert.match(openAi,/if\(jsonSchema\) body\.text = \{format:jsonSchema\}/);
  assert.match(openAi,/if\(d\.status==='incomplete'\)/);
  assert.match(turn,/maxTokens:VAL_WITNESSING_TURN_OUTPUT_TOKENS/);
  assert.match(turn,/maxTokens:VAL_WITNESSING_TURN_RETRY_OUTPUT_TOKENS/);
  assert.match(turn,/jsonSchema:VAL_WITNESSING_TURN_RESPONSE_FORMAT/);
  assert.match(turn,/incomplete structured output/);
  assert.match(turn,/timeoutMs:VAL_WITNESSING_TURN_TIMEOUT_MS/);
  assert.match(turn,/witness_lines/);
  assert.match(turn,/living_executive_graph/);
  assert.match(turn,/normalizePartnershipWitnessResponse/);
  assert.match(route,/generatePartnershipProtocolTurn\(\{card,rawResponse,priorImports\}\)/);
  assert.doesNotMatch(route,/composePartnershipProtocolNextQuestion/);
  assert.match(server,/app\.post\('\/api\/teach-val\/onboarding\/:id\/witnessing-cards\/:cardId\/confirm'[\s\S]*?composePartnershipProtocolNextQuestion/);
  assert.match(server,/nextQuestion/);
  assert.match(server,/openai_connection_required/);
  assert.match(server,/Your answer is still here\. Please try again\./);
});
